// angular-personal/src/app/components/game/game.component.ts
import { Component } from '@angular/core';
import { TabComponent, TabOption } from '@tc/tc-ngx-general';
import { TrooperMatchComponent } from '../games/trooper-match/trooper-match.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-game',
  imports: [TabComponent, TrooperMatchComponent, CommonModule],
  templateUrl: './game.component.html',
  styleUrl: './game.component.css'
})
export class GameComponent {

  tabs: TabOption[] = [
    {
      showTitle: "Trooper Match",
      actTitle: "tm"
    }
  ]

  activeTab: string = "tm";


}

<div class="container">
    <lib-tab [tabs]="tabs">
        <app-trooper-match *ngIf="activeTab == 'tm'"></app-trooper-match>
    </lib-tab>  
</div>

// react-personal/src/components/GameComponent.tsx
import { Container } from "react-bootstrap";
import React from "react";
import type { JSX } from "react";
import TrooperMatchComponent from "./games/TrooperMatchComponent";
import { TabComponent, type TabOption } from "@tc/tc-rc-general";

export default function GameComponent(){

    const [activeTab, setActiveTab] = React.useState<string>("tm");

    const [tabs, setTabs] = React.useState<TabOption[]>([
        {
        showTitle: "Trooper Match",
        actTitle: "tm"
        }
    ]);

    function getGame() : JSX.Element {
        if(activeTab == "tm") return <TrooperMatchComponent/>
        
        return <></>;
    }

    return (
        <Container>
            <TabComponent 
                tabs={tabs} 
                onTabSelectSet={setTabs} 
                onTabSelectStr={setActiveTab}
            >
                {getGame()}
            </TabComponent>
        </Container>
    )
}
