// react-personal/src/components/ArtGalleryComponent.tsx
import { Button, Container, Form } from "react-bootstrap";

import styles from "./component.module.css";
import React from "react";

import images from '../assets/Images.json';

import lessThan from "../assets/Less_than.png";
import xImage from "../assets/icons/X-image.png";
import { StylesService } from "@tc/tc-rc-general";

type ImageEntry = {
    url: string;
    artist: string;
    title: string;
    desc: string;
    isSelf: boolean;
    tags: string[];
}


export default function ArtGalleryComponent() {

    const startImage: ImageEntry = {
        url: "",
        artist: "",
        title: "",
        desc: "",
        isSelf: true,
        tags: []
    };

    const [showCommissions, setShowCommissions] = React.useState(true);
    const [showSelfArt, setShowSelfArt] = React.useState(true);
    const [searchTerm, setSearchTerm] = React.useState('');

    const [useGallery, setUseGallery] = React.useState(false);
    const [showPanel, ] = React.useState(false);
    //const [xButtonHover, setXButtonHover] = React.useState(false);

    const [, setImageWidth] = React.useState(500);
    const [viewHeight, setViewHeight] = React.useState(600);
    const [galleryImageHeight, setGalleryImageHeight] = React.useState('600px');
    const [cardHeight, setCardHeight] = React.useState('600px');
    const [cardWidth, setCardWidth] = React.useState('500px');
    const [treatAsMobile, setTreatAsMobile] = React.useState(window.innerWidth < 500);

    const [selectedImage, setSelectedImage] = React.useState(startImage);
    const [currentIndex, setCurrentIndex] = React.useState(0);
    const [indexIsFinal, setIndexIsFinal] = React.useState(false);


    const panelRef = React.createRef<HTMLDivElement>();

    const ss: StylesService = StylesService.getInstance();


    function filterImages(imageList: ImageEntry[]) : ImageEntry[] {
        let ret: ImageEntry[] = [];
        if(showCommissions && showSelfArt) {
            ret = imageList;
        } else if(showCommissions) {
            ret = imageList.filter((ie: ImageEntry) => !ie.isSelf);
        } else if(showSelfArt) {
            ret = imageList.filter((ie: ImageEntry) => ie.isSelf);
        }
        let term = searchTerm.trim();
        if(term.length){
            ret = ret.filter((ie: ImageEntry) => hasTag(term, ie));
        }
        return ret;
    }


    function hasTag(tag: string | undefined, entry: ImageEntry): boolean {
        if(!tag){
            return true;
        }
        let lTag = tag.toLowerCase();
        
        for(let t of entry.tags){
            let lt = t.toLowerCase();
            if(lt.indexOf(lTag) >= 0){
                return true;
            }
        }
        return false;
    }

    function updateSize() {
        
        let width = window.innerWidth;

        setTreatAsMobile(window.innerWidth < 500);

        setViewHeight(window.innerHeight);

        let tempWidth = (width - 35) / 6;
        if(tempWidth > 200) tempWidth = 200;

        setGalleryImageHeight(`${tempWidth}px`);
        tempWidth = Math.floor(tempWidth / 2 * 3);
        setCardHeight(`${tempWidth}px`);
        setCardWidth(`${tempWidth + 30}px`);

        setImageWidth(tempWidth);
    }
    window.addEventListener('resize', updateSize);

    //updateSize();

    function toggleTagView(
        ref: React.RefObject<HTMLDivElement | null>, isViewing: boolean){
        if(!ref.current) return;
        let classes = ref.current.className.split(' ');
        if(isViewing) {
            if(!classes.includes(styles.overExt))
                classes.push(styles.overExt);
        } else {
            classes = classes.filter((c: string) => c != styles.overExt);
        }

        ref.current.className = classes.join(' ');
    }

    function togglePanelView(isViewing: boolean) {
        if(!panelRef.current) return;

        panelRef.current.style.maxHeight = isViewing ? '100%' : '0';

    }

    function setImageEntryCaller(ie: ImageEntry, i: number) {
        setSelectedImage(ie);
        setCurrentIndex(i);
        togglePanelView(true);

        let filteredImages = filterImages(images);
        setIndexIsFinal(i == filteredImages.length - 1);
    }

    function switchImage(forward: boolean) {
        let filteredImages = filterImages(images);
        if(forward){
            if(currentIndex == filteredImages.length - 1)
            {
                setIndexIsFinal(true);
                return;
            }

            let nextIndex = currentIndex+1

            setCurrentIndex(nextIndex);
            setImageEntryCaller(filteredImages[nextIndex], nextIndex);
            if(nextIndex == filteredImages.length - 1)
            {
                setIndexIsFinal(true);
                return;
            }
        } else {
            if(currentIndex == filteredImages.length - 1){
                setIndexIsFinal(false);
            }

            if(!currentIndex) return;
            let prevIndex = currentIndex - 1;
            setCurrentIndex(prevIndex);
            setImageEntryCaller(filteredImages[prevIndex], prevIndex);
    }
    }

    function getGalleryElements() {
        return filterImages(images).map((entry: ImageEntry, index: number) => {

            const divRef = React.createRef<HTMLDivElement>();

            return (
                <li style={{height: galleryImageHeight}} className={ss.getElementItemClasses('')}>
            <div onMouseEnter={()=> toggleTagView(divRef, true)}   onMouseLeave={() => toggleTagView(divRef, false)}
                style={{
                    height: "100%",
                    alignItems: "center",
                    justifyContent: "center",
                    display: "flex",
                    position: "relative"}}
                onClick={() => setImageEntryCaller(entry, index)}>
                <img className={[styles.imageEntry, "mx-auto"].join(' ')} src={entry.url} alt={entry.title} />
                <div className={styles.overlay} ref={divRef}>
                    <span style={{color:"white"}}>{entry.title}</span>
                    <ul style={{listStyleType: "none"}}>
                        { entry.tags.map((tag: string) => ( <li style={{color:"white"}}>#{tag}</li> )) }
                    </ul>
                </div>
            </div>
        </li>
            );


        })
    }

    function getCardElements(){
        return filterImages(images).map((entry: ImageEntry, index: number) => { 

            const divRef = React.createRef<HTMLDivElement>();
            
            return (
                <li  className={ss.getElementItemClasses('')}>
                    <div className={styles.imageCard} style={{ width: cardWidth}}>
                        <div onMouseEnter={()=> toggleTagView(divRef, true)}   onMouseLeave={() => toggleTagView(divRef, false)}
                            className={styles.cardEntryWrapper} onClick={()=> setImageEntryCaller(entry, index)} style={{ height: cardHeight}}>
                            <img className={[styles.cardEntry, "mx-auto"].join(' ')} src={entry.url} alt={entry.title} />
                            <div className={styles.overlay} ref={divRef}>
                                <span style={{color:"white"}}>{entry.title}</span>
                                <ul style={{listStyleType: "none"}}>
                                    { entry.tags.map((tag: string) => ( <li style={{color:"white"}}>#{tag}</li> )) }
                                </ul>
                            </div>
                        </div>
                        <div style={{display: "flex"}}>
                            <p style={{ textAlign: "center" }}><b>Title: </b>{ entry.title }</p>
                        </div>
                    </div>
                </li>
            )
        })
    }

    const imageList = (useGallery && !treatAsMobile) ? 
            getGalleryElements():
            getCardElements(); 



    return (
        <Container onLoad={() => updateSize()}
        //  style={{
        //     backgroundColor:"rgb(63, 227, 248)",
        //     backgroundSize: "cover",
        //     backgroundRepeat: "repeat-y",
        //     minHeight: "100%"}}
            className={ss.getElementContainerClasses('')}
        >

            <div className={styles.flexAndCenter} style={{gap: "5px"}}>
                <Button variant="info" onClick={() => {
                        setShowCommissions(false);
                        setShowSelfArt(true);
                    }}>Self Art</Button>
                <Button variant="info" onClick={() => {
                        setShowCommissions(true);
                        setShowSelfArt(true);
                    }}>All Art</Button>
                <Button variant="info" onClick={() => {
                        setShowCommissions(true);
                        setShowSelfArt(false);
                    }}>Commissioned Art</Button>
                
            </div>


            <div style={{
                gap:"15px",
                flexWrap: "wrap",
                marginBottom: "10px"}}
                className={styles.flexAndCenter}
                //  *ngIf="imageWidth >= 500"
                >
                <div className="form-check">
                    <Form.Check id="galleryT" type="radio" name="galleryType" checked={ useGallery } onClick={()=> setUseGallery(true)} />
                    <Form.Label for="gelleryT" class="form-check-label">Use Gallery</Form.Label>
                </div>
                <div className="form-check">
                    <Form.Check id="galleryT" type="radio" name="galleryType" checked={ !useGallery } onClick={()=> setUseGallery(false)} />
                    <Form.Label for="gelleryT" class="form-check-label">Use Cards</Form.Label>
                </div>
            </div>
            <br/>







    <ul className={styles.imageGal}>
        {imageList}
    </ul> 


    <div style={{height:"300px"}}></div>


    <div ref={panelRef} className={styles.imgPanel}
        style={{
            border: "3px solid lightgreen",
            position: "fixed",
            bottom: "0px",
            width: "100%",
            marginLeft: "-15px",
            maxWidth:"inherit",
            backgroundColor: "rgb(63, 227, 248)",
            zIndex: 10 ,
            maxHeight: "0",
            display: "flex",
            flexDirection: "column"}}>
    {
        selectedImage.url.length ?
    
(
    <div className={styles.imageViewer} style={{maxHeight : viewHeight * 0.75 + 'px'}}>
        <div className={styles.switchHolder}>

            {
                currentIndex ? 
                    (
                        <img src={lessThan} style={{position: "absolute", left:0}} className={styles.browseImg} onClick={() => switchImage(false)} />
                    ) : (<div></div>)
            }


            {
                !indexIsFinal ? 
                    (
                        <img src={lessThan} style={{position: "absolute", right:0}} className={[styles.browseImg,  styles.imgRev].join(' ')} onClick={() => switchImage(true)} />
                    ) : (<div></div>)
            }
            
            
        </div>
        
        <img src={selectedImage.url} />
        
    </div>) : <div></div>
    
    }
    
    <div style={{flexGrow: 1}}>

        <div style={{
            display: "flex", flexDirection: "column", margin: "10px", justifyContent: "center", alignItems: "center", gap:"5px"}}>
            <div style={{display: "flex", flexDirection: "row", margin: "5px", justifyContent: "center", alignItems: "center", gap:"10px", width:"100%"}}>
                <Form.Control type="text" placeholder="Search By Tag" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} />
                <div className={styles.redButtonContainer}>
                        
                    <button onClick={() => togglePanelView(false)}><img src={xImage} alt="exit button" /></button>
                </div>
            </div>
        </div>
        
        {
            selectedImage.url.length ?
                (
                    <div>
                <p style={{textAlign: "center", margin:"5px"}}><b>Title: </b>{ selectedImage.title }</p>
                <p style={{textAlign: "center", margin:"5px"}}><b>Artist: </b>{ selectedImage.artist}</p>
                <p style={{textAlign: "center", margin:"5px"}}><b>Desc: </b>{ selectedImage.desc }</p>
                <div style={{display: "flex", justifyContent: "center", padding: "5px"}}>
                    <Button variant="info" onClick={() => setImageEntryCaller(startImage, 0)}>Remove Stats</Button>
                </div>
                </div>
                ) : ( <div></div>)
        }

        </div>

    
    
    </div>

    {
        showPanel ? 

        (<div></div>) :
        (<Button variant="primary" className={styles.actSearch} onClick={() => (setImageEntryCaller(selectedImage, currentIndex))}>Show Search</Button>)

    }



    


        </Container>
    );
}

// angular-personal/src/app/components/art-gallery/art-gallery.component.ts
import { CommonModule } from '@angular/common';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { FormsModule } from '@angular/forms';
import { AfterContentInit, Component, HostListener } from '@angular/core';
import { ImageFilterPipe } from '../../pipes/image-filter.pipe';
import { HttpClient } from '@angular/common/http';
import { ImageEntry } from '../../models/image-entry';
import { ElementContainerDirective, ElementItemDirective } from '@tc/tc-ngx-general';


@Component({
  selector: 'app-art-gallery',
  imports: [CommonModule, FormsModule, ImageFilterPipe, 
    ElementContainerDirective, ElementItemDirective],
  templateUrl: './art-gallery.component.html',
  styleUrl: './art-gallery.component.css',
  animations: [
    trigger('imageTranslate', [
      state('collapse', style({ height: '0px', overflow: 'hidden'})),
      state('expanded', style({ height: '*', overflow: 'hidden'})),
      transition('collapse => expanded', [ animate('0.33s')]),
      transition('expanded => collapse', [animate('0.33s')])
    ]),
    trigger('xHover',[
      state('hover', style({background: 'rgba(255,0,0,1.0)'})),
      state('leave', style({background: 'rgba(0,0,0, 0.0'})),
      transition('hover => leave', [ animate('0.33s')]),
      transition('leave => hover', [ animate('0.33s')])
    ]),
    trigger('onShowGallery', [
      state('doShow', style({ height: '*'})),
      state('doHide', style({ height: '0px'})),
      transition('doShow => doHide', [ animate('0.33s')]),
      transition('doHide => doShow', [ animate('0.33s')])
    ])
  ]
})
export class ArtGalleryComponent implements AfterContentInit{
  showCommissions = true;
  showSelfArt = true;

  searchTerm= "";

  useGallery:boolean = false;
  showPanel: boolean = false;
  xButtonHover: boolean = false;

  imageWidth: number = 500;
  viewHeight: number = 600;
  setHover(setBHover: boolean){
    this.xButtonHover = setBHover;
  }

  setUseGallery(ug: boolean){
    this.useGallery = ug;
  }


  doShowCommissions(){
    this.showCommissions = true;
    this.showSelfArt = false;
  }

  doShowSelfArt(){
    this.showCommissions = false;
    this.showSelfArt = true;
  }

  doShowBoth(){
    
    this.showCommissions = true;
    this.showSelfArt = true;
  }

  @HostListener('window:resize', ['$event'])
  onResize(event: any) {
    this.adjustImages(event.target.innerWidth, event.target.innerHeight);
  }

  adjustImages(width: any, height: any){

    this.viewHeight = height;

    this.imageWidth = (width - 35) / 6;
    console.log(`Image Width = ${this.imageWidth} from ${width}`);
    if(this.imageWidth > 200) this.imageWidth = 200;

    this.galleryImageHeight = `height: ${this.imageWidth}px`;
    this.imageWidth = Math.floor(this.imageWidth / 2 * 3);
    this.cardHeight = `height: ${this.imageWidth}px`;
    this.cardWidth = `width: ${this.imageWidth + 30}px`;
  }

  images: ImageEntry[];

  selectedImage: ImageEntry | undefined;

  galleryImageHeight: string = "height: 200px";
  cardWidth: string = "width: 330px";
  cardHeight: string = "height: 300px";

  imageFilter: ImageFilterPipe = new ImageFilterPipe();

  currentIndex: number = 0;
  indexIsFinal: boolean = false;

  constructor(private client: HttpClient){
    this.images = [];
    this.prepImages();
  }
  ngAfterContentInit(): void {
    this.adjustImages(window.innerWidth, window.innerHeight);
  }
  ngOnInit(): void {
    this.adjustImages(window.innerWidth, window.innerHeight);
  }

  prepImages(){
    this.client.get<ImageEntry[]>('assets/Images.json').subscribe((entries: ImageEntry[]) => {
      this.images = entries;
    })
  }

  setImageEntry(sel: ImageEntry|undefined, index: number = 0){
    this.selectedImage = sel;
    this.showPanel = true;
    this.currentIndex = index;

    let filteredImages = this.imageFilter.transform(this.images, this.showSelfArt, this.showCommissions, this.searchTerm)
    // if(this.currentIndex == filteredImages.length - 1)
    //   {
    //     this.indexIsFinal = true;
    //     return;
    //   }

    this.indexIsFinal = this.currentIndex == filteredImages.length - 1;
  }

  hideGallery(){
    this.showPanel = false;
  }

  toggleTagView(entry: ImageEntry, show: boolean){
    entry.isHovering = show;
  }

  switchImage(forward: boolean){
    let filteredImages = this.imageFilter.transform(this.images, this.showSelfArt, this.showCommissions, this.searchTerm)
    if(forward){
      if(this.currentIndex == filteredImages.length - 1)
      {
        this.indexIsFinal = true;
        return;
      }

      this.currentIndex++;
      this.setImageEntry(filteredImages[this.currentIndex], this.currentIndex);
      if(this.currentIndex == filteredImages.length - 1)
      {
        this.indexIsFinal = true;
        return;
      }
    } else {
      if(this.currentIndex == filteredImages.length - 1){
        this.indexIsFinal = false;
      }

      if(!this.currentIndex) return;
      this.currentIndex--;
      this.setImageEntry(filteredImages[this.currentIndex], this.currentIndex);
    }
  }
}

<div appElementContainer class="container">

    <div class="flex-and-center" style="gap: 5px;">
        <button class="btn btn-info" (click)="doShowSelfArt()">Self Art</button>
        <button class="btn btn-info" (click)="doShowBoth()">All Art</button>
        <button class="btn btn-info" (click)="doShowCommissions()">Commissioned Art</button>
    </div>


    <div style="gap:15px; flex-wrap: wrap; margin-bottom: 10px;" class="flex-and-center" *ngIf="imageWidth >= 500">
        <div class="form-check">
            <input id="galleryT" class="form-check-input" type="radio" formGroup="galleryType" name="galleryType" (click)="setUseGallery(true)">
            <label for="gelleryT" class="form-check-label">Use Gallery</label>
        </div>
        <div class="form-check">
            <input id="galleryF" class="form-check-input" type="radio" formGroup="galleryType" name="galleryType" (click)="setUseGallery(false)" checked>
            <label for="galleryF" class="form-check-label">Use Cards</label>
        </div>
    </div>
    <br>
    
    <!-- <div class="gallery">
            <img *ngFor="let entry of images | imageFilter:showSelfArt:showCommissions" class="imageEntry" src="{{entry.url}}" alt="{{entry.title}}">
    
    </div>  -->
    
    
    
    
    
        <ul class="image-gal" *ngIf="useGallery && imageWidth >= 500">
            <li [style]="galleryImageHeight" *ngFor="let entry of images | imageFilter:showSelfArt:showCommissions:searchTerm" appElementItem>
                <div (mouseenter)="toggleTagView(entry, true)" (mouseleave)="toggleTagView(entry, false)" style="height: 100%; align-items: center; justify-content: center; display: flex; position: relative;" (click)="setImageEntry(entry)">
                    <img class="imageEntry mx-auto" src="{{entry.url}}" alt="{{entry.title}}">
                    <div class="overlay" [@imageTranslate]="entry.isHovering ? 'expanded' : 'collapse'">
                        <span style="color:white">{{entry.title}}</span>
                        <ul style="list-style-type: none;">
                            <li style="color:white" *ngFor="let tag of entry.tags">#{{tag}}</li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul> 
    
        <ul class="image-gal" *ngIf="!useGallery || imageWidth < 500">
            <li *ngFor="let entry of images | imageFilter:showSelfArt:showCommissions:searchTerm; index as i" appElementItem>
                <div class="imageCard" [style]="cardWidth">
                    <div (mouseenter)="toggleTagView(entry, true)" (mouseleave)="toggleTagView(entry, false)" 
                        class="cardEntryWrapper" (click)="setImageEntry(entry, i)" [style]="cardHeight">
                        <img class="cardEntry mx-auto" src="{{entry.url}}" alt="{{entry.title}}">
                        <div class="overlay" [@imageTranslate]="entry.isHovering ? 'expanded' : 'collapse'">
                            <span style="color:white">{{entry.title}}</span>
                            <ul style="list-style-type: none;">
                                <li style="color:white" *ngFor="let tag of entry.tags">#{{tag}}</li>
                            </ul>
                        </div>
                    </div>
                    <div style="display: flex;">
                        <p style="text-align: center;"><b>Title: </b>{{ entry.title }}</p>
                    </div>
                </div>
            </li>
        </ul>
    
        <div style="height:300px"></div>
    <!-- </div> -->

    <button *ngIf="!showPanel" class="btn btn-primary act-search" (click)="setImageEntry(undefined)">Show Search</button>
    
    <div [@onShowGallery]="showPanel ? 'doShow' : 'doHide'" 
        style="border: 3px solid lightgreen; position: fixed; bottom: 0px; width: 100%; margin-left:-15px;max-width:inherit; background-color: rgb(63, 227, 248); z-index: 10; max-height: 100vh;
  display: flex;
  flex-direction: column;">
        <div *ngIf="selectedImage" class="image-viewer" [style]="'max-height : ' + viewHeight * 0.8 + 'px'">
            <div class="switch-holder">
                <img src="assets/Less_than.png" style="left:0" class="browse-img" *ngIf="currentIndex" (click)="switchImage(false)">
                <img src="assets/Less_than.png" class="browse-img img-rev" *ngIf="!indexIsFinal && currentIndex" (click)="switchImage(true)">
                
                <img src="assets/Less_than.png" style="position: absolute; right:0" class="browse-img img-rev" *ngIf="!currentIndex" (click)="switchImage(true)">
                
            </div>
            
            <img [src]="selectedImage.url">
            
        </div>
        <div style="flex-grow: 1;">
            <div style="display: flex; flex-direction: column ;margin:10px; justify-content: center; align-items: center; gap:5px;">
                <div style="display: flex; flex-direction: row ;margin:5px; justify-content: center; align-items: center; gap:10px;width:100%">
                    <input type="text" class="form-control" placeholder="Search By Tag" [(ngModel)]="searchTerm">
                    <div class="red-button-container" [@xHover]="xButtonHover ? 'hover' : 'leave'" (mouseenter)="setHover(true)" (mouseleave)="setHover(false)">
                            
                        <button (click)="hideGallery()"><img src="assets/icons/X-image.png" alt="exit button"></button>
                    </div>
                </div>
            </div>
            
            <p *ngIf="selectedImage" style="text-align: center; margin:5px;"><b>Title: </b>{{ selectedImage.title }}</p>
            <p *ngIf="selectedImage" style="text-align: center; margin:5px;"><b>Artist: </b>{{ selectedImage.artist}}</p>
            <p *ngIf="selectedImage" style="text-align: center; margin:5px;"><b>Desc: </b>{{ selectedImage.desc }}</p>
            <div *ngIf="selectedImage" style="display: flex; justify-content: center; padding: 5px">
                <button class="btn btn-info" (click)="setImageEntry(undefined)">Remove Stats</button>
            </div>
        </div>

        
    </div>
    
</div>
