// angular-personal/src/app/components/games/trooper-match/trooper-match.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatchTracker } from '../../../models/match-tracker';

@Component({
  selector: 'app-trooper-match',
  imports: [CommonModule],
  templateUrl: './trooper-match.component.html',
  styleUrl: './trooper-match.component.css'
})
export class TrooperMatchComponent {
  picIndex: String[];

  arrays: any[];
  picIndex2: String[];
  picIndexHolder: String[];
  counter: number;

  resp: boolean;
  showTable:boolean;
  showMessage: boolean;

  doubleImageIndex: MatchTracker[][];

  // Selections
  selectedImg: any;

  constructor() { 
    this.picIndex = [
      '076.jpg',
      '078.jpg',
      '079.jpg',
      '080.jpg',
      'WP_20150107_005.jpg'
    ];

    this.arrays = [];
    this.picIndex2 = [];
    this.picIndexHolder = [];
    this.counter = 0;
    this.resp = true;
    this.showTable = this.showMessage = false;
    this.selectedImg = null;
    this.doubleImageIndex = [];
    this.refreshTable();
  }

  refreshTable() {

    
    for(let c = 0; c < 2; c++){
      let column = [];
      for(let r = 0; r < 5; r++) {
        let m = new MatchTracker();
        m.img = 'assets/trooper/holder.png';
        column.push(m);
      }
      this.doubleImageIndex.push(column);
    }
  }

  ngOnInit(): void {
  }

  deleteElement(arr:any[], ind:number) {
    if(ind >= 0 && ind < arr.length) {
        let temp = arr[arr.length - 1];
        arr[arr.length -1] = arr[ind];
        arr[ind] = temp;
        arr.pop();
    }
  }

  generateGame() {
    this.doubleImageIndex = [];
    this.refreshTable();
    this.counter = 0;
    this.showTable = this.showMessage = false;

    this.picIndex2 = [];
    this.picIndexHolder = [];
    this.arrays = [];

    for(let c = 0; c < 5; c++) {
      let rand = Math.floor(Math.random() * 100) % this.picIndex.length;

      this.picIndexHolder.push(this.picIndex[rand]);
      this.picIndexHolder.push(this.picIndex[rand]);

      this.picIndex2.push(this.picIndex[rand]);
      this.deleteElement(this.picIndex, rand);
    }

    this.picIndex = this.picIndex2;
    this.picIndex2 = [];

    for(let c = 0; c < 5; c++) {

      var arrayE1 = [];
      for(let rust = 0; rust < 2; rust++) {
          let rand = Math.floor(Math.random() * 100)  % this.picIndexHolder.length;
          arrayE1.push({img :this.picIndexHolder[rand], stat: 0});
          this.deleteElement(this.picIndexHolder, rand);
      }

      this.arrays.push(arrayE1);
    }
    this.showTable = true;
  }

  onSelect(n: String) {
    if (!this.resp) {
      return;
    }

    let nums = n.split(':');
            let row = Number.parseInt(nums[1]);
            let col = Number.parseInt(nums[0]);

            let selElement = this.arrays[row][col];
            if(selElement.stat > 0) {
              return;
            }

            if(selElement.stat == 0) {
                selElement.stat = 1;
            }
            
            
            
            this.counter++;

            this.doubleImageIndex[col][row].img = `assets/trooper/${selElement.img}`;

            if(this.selectedImg) {

                let selectedImg2 = {col,row};

                if(this.doubleImageIndex[this.selectedImg.col][this.selectedImg.row].img == this.doubleImageIndex[selectedImg2.col][selectedImg2.row].img) {
                  this.doubleImageIndex[this.selectedImg.col][this.selectedImg.row].stat = 2;
                  this.doubleImageIndex[selectedImg2.col][selectedImg2.row].stat = 2;
                    this.selectedImg = null;

                    if(this.checkWin()) {
                        this.showMessage = true;
                    }

                } else {
                    this.resp = false;
                    setTimeout( () => {
                      this.doubleImageIndex[this.selectedImg.col][this.selectedImg.row].img = 'assets/trooper/holder.png';
                      this.doubleImageIndex[selectedImg2.col][selectedImg2.row].img = 'assets/trooper/holder.png';

                      this.arrays[this.selectedImg.row][this.selectedImg.col].stat = 0;
                      this.arrays[selectedImg2.row][selectedImg2.col].stat = 0;

                        this.selectedImg = undefined;
                        this.resp = true;
                    }, 2000);
                }
            } else {
                this.selectedImg = {col, row};
            }
  }

  checkWin()
  {
    for(let rust = 0; rust < this.doubleImageIndex.length; rust++) {
      for(let c = 0; c < this.doubleImageIndex[rust].length; c++) {
        if( this.doubleImageIndex[rust][c].stat != 2) {
          return false;
        }
      }
    }
    return true;
  }
}

    <div class="matchCenter">
        <button id="gridSubmit" class="btn btn-primary" (click)="generateGame()" style="padding: 20px">Generate Game</button>
    </div>
    <div class="matchCenter">
        <table id="game" *ngIf="showTable">
            <tr>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[0][0].img" (click)="onSelect('0:0')">
                </td>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[1][0].img" (click)="onSelect('1:0')">
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[0][1].img" (click)="onSelect('0:1')">
                </td>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[1][1].img" (click)="onSelect('1:1')">
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[0][2].img" (click)="onSelect('0:2')">
                </td>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[1][2].img" (click)="onSelect('1:2')">
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[0][3].img" (click)="onSelect('0:3')">
                </td>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[1][3].img" (click)="onSelect('1:3')">
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[0][4].img" (click)="onSelect('0:4')">
                </td>
                <td>
                    <img width="100" height="100" [src]="doubleImageIndex[1][4].img" (click)="onSelect('1:4')">
                </td>
            </tr>
        </table>
    </div>
    <div 
        class="header-padder"
        *ngIf="showMessage"
    >
        <h3 id="message" >Congradulations! You completed this game in {{counter}} tries!<br>Press 'Generate Game' to play again!</h3>
    </div>

// react-personal/src/components/games/TrooperMatchComponent.tsx
import React from "react";
import styles from "../component.module.css";
import {Button} from 'react-bootstrap';


import { StylesService } from "@tc/tc-rc-general";

export default function TrooperMatchComponent() {

    let startDImageIndex: { img: string; stat: number; }[][] = [];
    let startArray: {
        img: string;
        stat: number;
    }[][] = [];

    let startSelection: {col: number, row: number } = {col:-1,row:-1};

    const [showTable, setShowTable] = React.useState(false);
    const [showMessage, setShowMessage] = React.useState(false);
    const [resp, setResp] = React.useState(true);

    const [doubleImageIndex, setDoubleImageIndex] = React.useState(startDImageIndex);
    const [picIndex, setPicIndex] = React.useState([
        "assets/trooper/WP_20150107_005.jpg",
        "assets/trooper/076.jpg",
        "assets/trooper/078.jpg",
        "assets/trooper/079.jpg",
        "assets/trooper/080.jpg"
    ]);
    
    const [arrays, setArrays] = React.useState(startArray);
    
    const [counter, setCounter] = React.useState(0);

    const [selectedImg, setSelectedImg] = React.useState(startSelection);

    const ss: StylesService = StylesService.getInstance();

    function checkWin()
    {
      for(let rust = 0; rust < doubleImageIndex.length; rust++) {
        for(let c = 0; c < doubleImageIndex[rust].length; c++) {
          if( doubleImageIndex[rust][c].stat != 2) {
            return false;
          }
        }
      }
      return true;
    }


    function refreshTable() {
        let tempIndex = [];
        for(let c = 0; c < 2; c++){
            let column = [];
            for(let r = 0; r < 5; r++) {
              let m = {
                img: "assets/trooper/holder.png",
                stat: 0
              }
              column.push(m);
            }
            tempIndex.push(column);
        }
        setDoubleImageIndex(tempIndex);
        
    }

    function deleteElement(arr:any[], ind:number) {
        if(ind >= 0 && ind < arr.length) {
            let temp = arr[arr.length - 1];
            arr[arr.length -1] = arr[ind];
            arr[ind] = temp;
            arr.pop();
        }
      }

    function generateGame() {
        refreshTable();

        setCounter(0);
        setShowMessage(false);
        //setShowTable(false);

        let picIndex2: string[] = [];

        let picIndexHolder: string[] = [];

        let tempArrays:{
            img: string;
            stat: number;
        }[][] = [];
        setArrays([]);



        for(let c = 0; c < 5; c++) {
            let rand = Math.floor(Math.random() * 100) % picIndex.length;
      
            picIndexHolder.push(picIndex[rand]);
            picIndexHolder.push(picIndex[rand]);
      
            picIndex2.push(picIndex[rand]);
            deleteElement(picIndex, rand);
          }
      
          setPicIndex(picIndex2);
      
          for(let c = 0; c < 5; c++) {
      
            var arrayE1 = [];
            for(let rust = 0; rust < 2; rust++) {
                let rand = Math.floor(Math.random() * 100)  % picIndexHolder.length;
                arrayE1.push({img :picIndexHolder[rand], stat: 0});
                deleteElement(picIndexHolder, rand);
            }
      
            tempArrays.push(arrayE1);
          }
          setArrays(tempArrays);
          setShowTable(true);
    }

    function onSelect(col: number, row: number) {
        if (!resp) {
            return;
        }

        let selElement = arrays[row][col];
        if(selElement.stat > 0) {
            return;
        }
      
        if(selElement.stat == 0) {
            selElement.stat = 1;
        }
                  
        setCounter(counter+1);      
                  
      
        doubleImageIndex[col][row].img = selElement.img;
      
        if(selectedImg.col >= 0) {
      
            let selectedImg2 = {col,row};
      
            if(doubleImageIndex[selectedImg.col][selectedImg.row].img == doubleImageIndex[selectedImg2.col][selectedImg2.row].img) {
                doubleImageIndex[selectedImg.col][selectedImg.row].stat = 2;
                doubleImageIndex[selectedImg2.col][selectedImg2.row].stat = 2;
                setSelectedImg({col:-1,row:-1});
      
                if(checkWin()) {
                    setShowMessage(true);
                }
      
            } else {
                setResp(false);
                setTimeout( () => {
                    doubleImageIndex[selectedImg.col][selectedImg.row].img = "assets/trooper/holder.png";
                    doubleImageIndex[selectedImg2.col][selectedImg2.row].img = "assets/trooper/holder.png";
      
                    arrays[selectedImg.row][selectedImg.col].stat = 0;
                    arrays[selectedImg2.row][selectedImg2.col].stat = 0;
      
                    setSelectedImg({col:-1,row:-1});
                    setResp(true);
                }, 2000);
            }
        } else {
            setSelectedImg({col, row});
        }
    }


    return (
        <div className={ss.getElementItemClasses(styles.baseBackground)} style={{overflowY: "auto"}}>
            <div className={styles.matchCenter}>
                <Button id="gridSubmit" variant="primary" onClick={generateGame} style={{padding: "20px"}}>Generate Game</Button>
            </div>
    <div className={styles.matchCenter}>

        {
            showTable && 

            <table id="game">
            <tr>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[0][0].img} onClick={() => onSelect(0,0)} />
                </td>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[1][0].img} onClick={() => onSelect(1,0)} />
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[0][1].img} onClick={() => onSelect(0,1)} />
                </td>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[1][1].img} onClick={() => onSelect(1,1)} />
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[0][2].img} onClick={() => onSelect(0,2)} />
                </td>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[1][2].img} onClick={() => onSelect(1,2)} />
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[0][3].img} onClick={() => onSelect(0,3)} />
                </td>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[1][3].img} onClick={() => onSelect(1,3)} />
                </td>
            </tr>

            <tr>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[0][4].img} onClick={() => onSelect(0,4)} />
                </td>
                <td>
                    <img width="100" height="100" src={doubleImageIndex[1][4].img} onClick={() => onSelect(1,4)} />
                </td>
            </tr>
        </table>
        }

        
    </div>

        { showMessage &&
        
        <div 
        className={styles.headerPadder}
    >
        <h3 id="message" >Congradulations! You completed this game in {counter} tries!<br/>Press 'Generate Game' to play again!</h3>
    </div>
        }


    
        </div>
    );
}
